default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres # docker-compose.ymlの記載内容と同じ値に設定
  password: postgres # docker-compose.ymlの記載内容と同じ値に設定
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
